### ISSUE TITLE
Typos in specification

### ISSUE THREAD

**Issue by Tarolrr** [BroadbandForum/usp#1]
Several typos in word "WiFi" in message examples in [https://github.com/BroadbandForum/usp/blob/master/specification/messages/index.md](https://github.com/BroadbandForum/usp/blob/master/specification/messages/index.md)
Since paths in USP are case-sensitive, following example (page 125) wouldn't work:
```protobuf
GetSupportedDM {
    obj_paths {
        obj_path : "Device.Wifi."
    }
    first_level_only : false
    return_commands : true
    return_events : true
    return_params : true
}
```
Same typo in several other places in document

**Comment by jswalls** [comment]
Thanks @Tarolrr. We'll push this into our 1.0.1 fixes that should be released in a few weeks.
