### ISSUE TITLE
Not deleted leftover field

### ISSUE THREAD

**Issue by Tarolrr** [BroadbandForum/usp#2]
Field DiscoverObject in GetSupportedDM message doesn't encounter anywhere else in specification and .proto files, but one these several lines [https://github.com/BroadbandForum/usp/blame/master/specification/messages/index.md#L1537](https://github.com/BroadbandForum/usp/blame/master/specification/messages/index.md#L1537)

**Comment by jswalls** [comment]
We've noted this and it will be removed in our 1.0.1 release.
