### ISSUE TITLE
Extending the data model

### ISSUE THREAD

**Issue by zr-her** [BroadbandForum/usp#23]
Hello,

is it possible to extend the data model (e.g. to add other device parameters to the DeviceInfo Object or to add other states for the Deployment/Execution Units)? 

If so, can this be achieved via the [data model template](https://data-model-template.broadband-forum.org/)? Additionally, would the extension of the data model cause failures of the [USP conformance tests](https://usp-test.broadband-forum.org/)? 

Thanks!

**Comment by jswalls** [comment]
Hello! The answer to your question is yes, it is possible to extend the data model as defined here:

https://data-model-template.broadband-forum.org/04-index-object-definitions.html#sec:vendor-specific-elements

This applies differently depending on what you are using it for, however. If you want to convey an Agent's capabilities out-of-band to another system or a human being in a standardized format, you will want to write an XML document using the data model schema that explains these extensions. If you want to convey this information to a USP Controller from the USP Agent that supports these extensions, these are conveyed directly in the GetSupportedDataModel Response.

That said, the use case here is important. Always consider whether or not a vendor extension is absolutely necessary, and if so, whether or not it can be contributed to the standards data model (via a [Broadband Forum Member](https://www.broadband-forum.org/join-broadband-forum)). Any vendor extension use will limit the interoperability of your solution. If you could, send us an email to info@broadband-forum.org and let us know what company, if any, you're working for. If your company is already a Member, we will be able to provide you with information on how to create a Member account and access this information. If your company is not a Member, we can share details on how to join for your company to consider.

For the conformance tests, as long as your system ALSO makes use of the standardized elements, it should not affect compliance. The required profiles to support a given feature are explained here: https://usp-test.broadband-forum.org/01-index-test-setup.html#sec:test-setup-and-execution
