### ISSUE TITLE
mtp-proxy: WebSocket Controller Support

### ISSUE THREAD

**Issue by SimonTate** [BroadbandForum/usp#5]
Hi,

Are there any further developments for the WebSocket controller support for the mtp-proxy code? What's the current state? Still getting the same corruption as it says in mtp-proxy/README.md?

Thanks,
Simon

**Comment by helpatbbf** [comment]
Thanks for your interest in the development of the WebSocket controller support for the mtp-proxy code. This project is published by the Broadband Forum organization and was created to support Plugfest events.

The Broadband Forum relies on the participation of our Members to shape the development of most of our work. We welcome corporations, non-profit organizations and individuals to contribute.  We are considering moving this project to a Broadband Forum [Open Broadband](https://www.broadband-forum.org/open-broadband/open-broadband-software) project to allow non-members to provide input in maintaining this code.  If you would like more information, please email info@broadband-forum.org and visit our website at [broadband-forum.org](https://www.broadband-forum.org/)
